config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  get 'fetch' => 'events#fetch'
  post 'events' => 'events#create'
end

app/models/event.rb
class Event
  attr_reader :meta_event

  def initialize meta_event
    @meta_event = meta_event
  end

  def starts_at
    meta_event.starts_at
  end

  def ends_at
    meta_event.ends_at
  end

  def as_json(options={})
    {
      id: meta_event.id,
      title: '',
      start: starts_at,
      end: ends_at
    }
  end

end

app/models/event_collection.rb
class EventCollection
  include Enumerable

  def initialize events
    @events = events.sort_by &:starts_at
  end

  def for_week week
    events = @events.select do |e|
      e.starts_at >= week[0] && e.starts_at <= week[1]
    end
    EventCollection.new events
  end

  def each &block
    @events.each do |event|
      block.call event
    end
  end
end

app/models/meta_event.rb
class MetaEvent < ActiveRecord::Base
  validates_presence_of :starts_at, :ends_at

  scope :non_repeating, -> { where repeat_until: nil, repeating_infinitely: false }
  scope :repeating, -> {
    t = MetaEvent.arel_table
    MetaEvent.where(t[:repeat_until].not_eq(nil).or(t[:repeating_infinitely].eq(true)))
  }

  def self.events_for_week week
    t = MetaEvent.arel_table
    non_repeating_meta_events_for_week = MetaEvent.non_repeating.where('starts_at >=? AND starts_at <= ?', week[0], week[1])
    repeating_meta_events_for_week = MetaEvent.repeating.where(
      t[:repeat_until].gteq(week[0]).or(t[:repeating_infinitely].eq(true))
    )
    events = non_repeating_meta_events_for_week.map { |me| me.events_for_week(week) }.flatten +
      repeating_meta_events_for_week.map { |me| me.events_for_week(week) }.flatten
    EventCollection.new events
  end

  def is_repeating?
    repeat_until.present? || repeating_infinitely?
  end

  def events_for_week week
    _e = Event.new self

    if !is_repeating? && starts_at >= week[0] && starts_at <= week[1]
      return [ _e ]
    elsif !is_repeating?
      return []
    end

    events = []

    repeating_date = starts_at
    i = -1
    while repeating_date < week[1]
      i += 1
      _e.starts_at = starts_at + (7 * i).days
      _e.ends_at   = ends_at   + (7 * i).days
      repeating_date = _e.starts_at + 7.days

      next if _e.starts_at < week[0]
      events << _e
      _e = _e.dup
    end

    events
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  end

  def fetch
    events = MetaEvent.events_for_week [ Time.parse(params[:start]), Time.parse(params[:end]) ]
    render json: events
  end

  def create
    @meta_event = MetaEvent.new event_params
    @meta_event.save
  end

  private
  def event_params
    params.require(:meta_event).permit([ :notes, :starts_at, :ends_at, :repeat_until, :repeating_infinitely ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_modal.html.erb
<div class='modal fade event-modal'>
  <div class='modal-dialog'>
    <div class='modal-content'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
        <h4 class="modal-title">Event form</h4>
      </div>
      <%= form_for MetaEvent.new, url: events_url, remote: true, method: :post, html: { class: 'form-horizontal' } do |f| %>
        <div class='modal-body'>
          <div class='alert alert-danger hide'></div>
          <div class='form-group'>
            <%= f.label :starts_at, class: 'col-sm-3 control-label' %>
            <div class='col-sm-9'>
              <%= f.text_field :starts_at, class: 'form-control starts-at' %>
            </div>
          </div>
          <div class='form-group'>
            <%= f.label :ends_at, class: 'col-sm-3 control-label' %>
            <div class='col-sm-9'>
              <%= f.text_field :ends_at, class: 'form-control ends-at' %>
            </div>
          </div>
          <div class='form-group'>
            <div class="col-sm-offset-3 col-sm-9">
              <div class="checkbox">
                <label><%= f.check_box :repeating_infinitely %> Repeating infinitely</label>
              </div>
            </div>
          </div>
          <div class='form-group'>
            <%= f.label :repeat_until, class: 'col-sm-3 control-label' %>
            <div class='col-sm-9'>
              <%= f.text_field :repeat_until, class: 'form-control' %>
            </div>
          </div>
          <div class='form-group'>
            <%= f.label :notes, class: 'col-sm-3 control-label' %>
            <div class='col-sm-9'>
              <%= f.text_field :notes, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class='modal-footer'>
          <button type='button' class='btn btn-default' data-dismiss='modal'>Close</button>
          <%= f.submit 'Submit', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/create.js.erb
$eventModal = $('.event-modal');
<% if @meta_event.errors.messages.present? %>
  $eventModal.find('.alert.alert-danger').html('<%= @meta_event.errors.full_messages.join("; ") %>').removeClass('hide');
<% else %>
  $eventModal.modal('hide');
  $('#calendar').fullCalendar('refetchEvents');
<% end %>

app/views/events/index.html.erb
<h1>Events#index</h1>
<p>Find me in app/views/events/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FullcalendarWithBackend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id='calendar'></div>
<%= render 'events/event_modal' %>

</body>
</html>